"""add users table

Revision ID: 7af20d172999
Revises: 2c8f1a9e3b7d
Create Date: 2026-06-11 23:36:29.051604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7af20d172999'
down_revision: Union[str, None] = '2c8f1a9e3b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
