"""add attachments to chat_messages

Revision ID: f7ef2c6c0df2
Revises: 5d56963da3d1
Create Date: 2026-06-17 23:55:44.987126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7ef2c6c0df2'
down_revision: Union[str, None] = '5d56963da3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'attachments')
    # ### end Alembic commands ###
